
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxicdma.h"

/*
* The configuration table for devices
*/

XAxiCdma_Config XAxiCdma_ConfigTable[XPAR_XAXICDMA_NUM_INSTANCES] =
{
	{
		XPAR_AXI_CDMA_0_DEVICE_ID,
		XPAR_AXI_CDMA_0_BASEADDR,
		XPAR_AXI_CDMA_0_INCLUDE_DRE,
		XPAR_AXI_CDMA_0_USE_DATAMOVER_LITE,
		XPAR_AXI_CDMA_0_M_AXI_DATA_WIDTH,
		XPAR_AXI_CDMA_0_M_AXI_MAX_BURST_LEN,
		XPAR_AXI_CDMA_0_ADDR_WIDTH
	},
	{
		XPAR_AXI_CDMA_1_DEVICE_ID,
		XPAR_AXI_CDMA_1_BASEADDR,
		XPAR_AXI_CDMA_1_INCLUDE_DRE,
		XPAR_AXI_CDMA_1_USE_DATAMOVER_LITE,
		XPAR_AXI_CDMA_1_M_AXI_DATA_WIDTH,
		XPAR_AXI_CDMA_1_M_AXI_MAX_BURST_LEN,
		XPAR_AXI_CDMA_1_ADDR_WIDTH
	},
	{
		XPAR_AXI_CDMA_2_DEVICE_ID,
		XPAR_AXI_CDMA_2_BASEADDR,
		XPAR_AXI_CDMA_2_INCLUDE_DRE,
		XPAR_AXI_CDMA_2_USE_DATAMOVER_LITE,
		XPAR_AXI_CDMA_2_M_AXI_DATA_WIDTH,
		XPAR_AXI_CDMA_2_M_AXI_MAX_BURST_LEN,
		XPAR_AXI_CDMA_2_ADDR_WIDTH
	},
	{
		XPAR_AXI_CDMA_3_DEVICE_ID,
		XPAR_AXI_CDMA_3_BASEADDR,
		XPAR_AXI_CDMA_3_INCLUDE_DRE,
		XPAR_AXI_CDMA_3_USE_DATAMOVER_LITE,
		XPAR_AXI_CDMA_3_M_AXI_DATA_WIDTH,
		XPAR_AXI_CDMA_3_M_AXI_MAX_BURST_LEN,
		XPAR_AXI_CDMA_3_ADDR_WIDTH
	}
};


